### ISSUE TITLE
Change direction of the switch control to activate dark mode

### ISSUE THREAD

**Issue by norlancd** [kenriortega/timezones-locations#3]
![image](https://user-images.githubusercontent.com/18106349/109408062-fedbdb80-7953-11eb-9300-3912761dc79d.png)

**Comment by kenriortega** [comment]
Thx for you help, this is my solution
![Screenshot_2021-03-04 React App(1)](https://user-images.githubusercontent.com/53656046/110054528-42a25c80-7d29-11eb-83a8-aab5b2b3b444.png)
![Screenshot_2021-03-04 React App](https://user-images.githubusercontent.com/53656046/110054537-47671080-7d29-11eb-83d1-68c4204ddd2e.png)


 if you find another issue please feel free to write it
